# Generated by Django 5.0.6 on 2024-07-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='cars/templates/images/produto-sem-imagem.jpg', null=True, upload_to='cars/'),
        ),
    ]
