# Generated by Django 5.0.6 on 2024-07-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='produto-sem-imagem.jpg', null=True, upload_to='cars/'),
        ),
    ]
