# Generated by Django 5.0.6 on 2024-07-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='../media/cars/default.jpg', null=True, upload_to='cars/'),
        ),
    ]
